spring:
  application:
    name: spring-ai-alibaba-openmanus
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-b0ac526ee44f4bb7b6c61cbcaea14b15
      chat:
        options:
          model: qwen-plus-latest
